title: Marcos G. Zimmermann
email: marcos@marcosz.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Meu nome é Marcos sou desenvolvedor e esse é meu blog.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social_links:
  twitter: marcosgz
  github: marcosgz
  linkedin: marcosz

sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
